# Nova S2S WebRTC Environment Configuration
# 
# Strategy: Minimal conda (system only), all Python packages via pip
# This completely avoids conda's aiortc/pylibsrtp dependency conflicts
#
name: nova-s2s-webrtc
channels:
  - conda-forge
dependencies:
  # System dependencies via conda (av installed separately for platform compatibility)
  - python=3.12
  - pip
  - ffmpeg
  - pkg-config
  - numpy=1.26.4  # Explicit version guarantee
  # Note: av installed separately via script for platform-specific version handling
  
  # All other Python packages installed via pip (see requirements.txt)